**We applied topic modelling for each dataset separately**

In [1]:
import csv
import pandas as pd
import pandas as pd
import re
import string
import nltk
from nltk.corpus import stopwords
import gensim
from gensim import corpora
from nltk.tokenize import word_tokenize

#Feminism Movement

Topic modelling for feminism dataset.. we extracted the topics for each stance' tweets separately

In [3]:
df = pd.read_csv('Real_train_feminism_664.csv')
df.head()

,ID,Target,Tweet,Stance
0,1009,Feminist Movement,Always a delight to see chest-drumming alpha m...,FAVOR
1,1010,Feminist Movement,Sometimes I overheat and want to take off my s...,FAVOR
2,1011,Feminist Movement,If feminists spent 1/2 as much time reading pa...,AGAINST
3,1012,Feminist Movement,"Stupid Feminists, the civilization you take fo...",AGAINST
4,1013,Feminist Movement,YOU'RE A GIRL AND HAVE A SEX DRIVE!? YOU MUST ...,FAVOR

In [4]:
Tweet=df[df['Stance']== 'FAVOR']['Tweet'] #choose the stance' tweets for topic modelling
Tweet.head()

0    Always a delight to see chest-drumming alpha m...
1    Sometimes I overheat and want to take off my s...
4    YOU'RE A GIRL AND HAVE A SEX DRIVE!? YOU MUST ...
5    Suns out....  Dresses out...  #StreetHarassmen...
6    Women's rights are #humanrights! Join the #CPD...
Name: Tweet, dtype: object

In [5]:
#pre-process the tweets before use the LDA model
nltk.download('punkt')
nltk.download('stopwords')
stops = set(stopwords.words("english"))
additional_stopwords = ["doesnt", "im", "dont", "rt","semst","feminist", "feminists"]  # remove specific words in Favor' tweets
#additional_stopwords = ["semst", "feminist", "feminists"]  # remove specific words in Against' tweets
#additional_stopwords = ["semst"]  # remove specific words in None' tweets
stops.update(additional_stopwords)

def preprocess(tweet):
  tokenlist=[]
  tweet = re.sub(r"http\S+|www\S+|https\S+", "", tweet)  # remove URLs
  tweet = re.sub(r"@\w+", "", tweet)  # remove usernames
  tokens = nltk.word_tokenize(tweet) #tokenization
  tokenlist= [w.lower() for w in tokens if w.isalpha()] #make each token in owest case and remove numbers and punctuations

  tokenlist= [word for word in tokenlist if not word in stops] #remove stop words
  return ' '.join([w for w in tokenlist])

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [6]:
# apply preprocessing
Tweet= Tweet.apply(preprocess)
Tweet.head()

0    always delight see alpha males hiss scuttle ba...
1    sometimes overheat want take shirt ca social e...
4                             girl sex drive must slut
5    suns dresses streetharassment daily life yesal...
6    women rights humanrights join cpdvoices twitte...
Name: Tweet, dtype: object

In [9]:
# create a dictionary
dictionary_Tweets = corpora.Dictionary([tweet.split() for tweet in Tweet])
# convert the tweets into a bag-of-words corpus (counts the frequency of each word)
corpus_Tweets=[]
for tweet in Tweet:
  tweet=tweet.split()
  text= dictionary_Tweets.doc2bow(tweet)
  corpus_Tweets.append(text)
print(corpus_Tweets[:1]) #viewing

[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1), (10, 1), (11, 1)]]

In [10]:
num_topics = 10
# built LDA model
lda_model = gensim.models.LdaModel(corpus_Tweets, num_topics=num_topics, id2word=dictionary_Tweets, passes=10)

**In the following Stances headings, we printed the topics as 5,10, or 15 number of topics**

##Feminism Favor Stance

In [ ]:
#10 topics
# Print the topics
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.040*"women" + 0.017*"get" + 0.017*"let" + 0.014*"gender" + 0.010*"ca" + 0.010*"know" + 0.010*"respect" + 0.010*"less" + 0.007*"male" + 0.007*"would"')
(1, '0.046*"women" + 0.033*"men" + 0.022*"equal" + 0.008*"must" + 0.008*"rights" + 0.008*"ugly" + 0.008*"world" + 0.008*"know" + 0.008*"change" + 0.008*"equality"')
(2, '0.027*"women" + 0.019*"man" + 0.016*"feminism" + 0.016*"need" + 0.014*"get" + 0.011*"female" + 0.011*"yesallwomen" + 0.011*"men" + 0.008*"would" + 0.008*"mean"')
(3, '0.013*"sexist" + 0.013*"women" + 0.009*"make" + 0.009*"misogynist" + 0.009*"views" + 0.009*"expression" + 0.009*"culture" + 0.009*"got" + 0.009*"feminist" + 0.009*"still"')
(4, '0.024*"man" + 0.020*"feminist" + 0.020*"equality" + 0.016*"want" + 0.008*"girls" + 0.008*"female" + 0.008*"bcs" + 0.008*"cooking" + 0.008*"stop" + 0.008*"ur"')
(5, '0.022*"women" + 0.018*"woman" + 0.018*"take" + 0.015*"need" + 0.015*"feminist" + 0.011*"men" + 0.011*"ugly" + 0.011*"etc" + 0.011*"call" + 0.011*"name"')
(6, '0.016*"women" + 0.016*"important" + 0.011*"girls" + 0.011*"equal" + 0.011*"want" + 0.011*"us" + 0.011*"gaming" + 0.011*"equally" + 0.011*"children" + 0.011*"makeup"')
(7, '0.022*"feminist" + 0.009*"gender" + 0.009*"time" + 0.009*"equality" + 0.009*"thank" + 0.009*"ugly" + 0.009*"told" + 0.009*"u" + 0.009*"glass" + 0.009*"bitch"')
(8, '0.025*"women" + 0.011*"right" + 0.011*"need" + 0.011*"even" + 0.011*"feminist" + 0.008*"girls" + 0.008*"called" + 0.008*"like" + 0.008*"want" + 0.008*"said"')
(9, '0.019*"equality" + 0.013*"like" + 0.013*"people" + 0.013*"yesallwomen" + 0.013*"see" + 0.013*"gender" + 0.013*"women" + 0.010*"feminists" + 0.010*"right" + 0.010*"even"')

In [ ]:
#5 topics
# print the topics
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.015*"ugly" + 0.009*"get" + 0.008*"equal" + 0.008*"even" + 0.008*"people" + 0.008*"females" + 0.008*"always" + 0.006*"women" + 0.006*"time" + 0.006*"gender"')
(1, '0.031*"women" + 0.020*"need" + 0.019*"feminist" + 0.013*"girls" + 0.012*"man" + 0.011*"people" + 0.010*"like" + 0.010*"feminism" + 0.008*"get" + 0.008*"men"')
(2, '0.024*"women" + 0.013*"woman" + 0.011*"feminist" + 0.007*"call" + 0.007*"patriarchy" + 0.007*"like" + 0.007*"etc" + 0.005*"right" + 0.005*"beauty" + 0.005*"rape"')
(3, '0.022*"men" + 0.021*"women" + 0.020*"equality" + 0.011*"want" + 0.011*"female" + 0.009*"woman" + 0.009*"yesallwomen" + 0.008*"right" + 0.008*"feminist" + 0.008*"would"')
(4, '0.028*"women" + 0.019*"equal" + 0.017*"feminist" + 0.011*"men" + 0.010*"feminists" + 0.010*"want" + 0.008*"rights" + 0.007*"pretty" + 0.007*"u" + 0.007*"social"')

In [ ]:
#15 topics
# print the topics
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.019*"men" + 0.019*"women" + 0.014*"equal" + 0.014*"feminist" + 0.014*"female" + 0.014*"time" + 0.009*"feminists" + 0.009*"social" + 0.009*"rights" + 0.009*"power"')
(1, '0.018*"woman" + 0.014*"etc" + 0.014*"either" + 0.014*"feminist" + 0.009*"even" + 0.009*"cooking" + 0.009*"rapist" + 0.009*"stay" + 0.009*"change" + 0.009*"feminism"')
(2, '0.026*"need" + 0.021*"feminism" + 0.016*"let" + 0.016*"gender" + 0.011*"make" + 0.011*"children" + 0.011*"want" + 0.011*"life" + 0.011*"people" + 0.011*"cats"')
(3, '0.035*"equality" + 0.025*"women" + 0.015*"gender" + 0.010*"let" + 0.010*"woman" + 0.010*"people" + 0.010*"america" + 0.010*"love" + 0.010*"ca" + 0.010*"politics"')
(4, '0.025*"women" + 0.020*"like" + 0.020*"yesallwomen" + 0.015*"wonder" + 0.015*"woman" + 0.015*"harassed" + 0.015*"sexually" + 0.015*"get" + 0.010*"even" + 0.010*"still"')
(5, '0.026*"ugly" + 0.020*"equal" + 0.013*"gaming" + 0.013*"life" + 0.013*"new" + 0.013*"need" + 0.013*"man" + 0.013*"yesallwomen" + 0.013*"got" + 0.013*"women"')
(6, '0.023*"man" + 0.023*"women" + 0.012*"city" + 0.012*"want" + 0.012*"bcs" + 0.012*"feminist" + 0.012*"helping" + 0.012*"beauty" + 0.012*"like" + 0.012*"work"')
(7, '0.031*"women" + 0.024*"get" + 0.018*"equality" + 0.012*"man" + 0.012*"feminist" + 0.012*"need" + 0.006*"woman" + 0.006*"society" + 0.006*"could" + 0.006*"ppl"')
(8, '0.041*"women" + 0.018*"girls" + 0.018*"like" + 0.012*"said" + 0.012*"everyone" + 0.012*"call" + 0.012*"called" + 0.012*"male" + 0.012*"would" + 0.012*"degrade"')
(9, '0.031*"equal" + 0.031*"women" + 0.021*"men" + 0.016*"right" + 0.016*"female" + 0.016*"feminist" + 0.011*"room" + 0.011*"full" + 0.011*"stop" + 0.011*"equality"')
(10, '0.037*"men" + 0.033*"women" + 0.023*"people" + 0.023*"feminists" + 0.019*"feminist" + 0.019*"equality" + 0.014*"want" + 0.014*"girls" + 0.014*"ugly" + 0.010*"telling"')
(11, '0.036*"women" + 0.021*"men" + 0.021*"feminist" + 0.016*"u" + 0.016*"woman" + 0.011*"pretty" + 0.011*"pride" + 0.011*"take" + 0.011*"genderequality" + 0.011*"enough"')
(12, '0.024*"feminist" + 0.020*"gender" + 0.010*"interview" + 0.010*"see" + 0.010*"century" + 0.010*"one" + 0.010*"yesallwomen" + 0.010*"important" + 0.010*"mean" + 0.010*"know"')
(13, '0.019*"women" + 0.013*"way" + 0.013*"turn" + 0.013*"man" + 0.013*"stop" + 0.013*"ur" + 0.013*"makeup" + 0.013*"want" + 0.013*"ca" + 0.013*"nudes"')
(14, '0.026*"women" + 0.013*"need" + 0.013*"well" + 0.013*"men" + 0.007*"festival" + 0.007*"art" + 0.007*"surely" + 0.007*"learned" + 0.007*"abusive" + 0.007*"create"')

##Feminism Against Stance

In [ ]:
#5 topics
# print the topics and their associated keywords
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.012*"feminism" + 0.010*"shit" + 0.007*"gamergate" + 0.006*"get" + 0.005*"male" + 0.005*"u" + 0.005*"love" + 0.005*"got" + 0.004*"much" + 0.004*"would"')
(1, '0.014*"men" + 0.013*"women" + 0.012*"make" + 0.012*"people" + 0.008*"get" + 0.008*"equal" + 0.008*"right" + 0.008*"gamergate" + 0.007*"rape" + 0.007*"feminism"')
(2, '0.015*"gamergate" + 0.008*"women" + 0.006*"like" + 0.006*"need" + 0.006*"time" + 0.006*"men" + 0.005*"dear" + 0.005*"girls" + 0.005*"every" + 0.005*"male"')
(3, '0.030*"women" + 0.022*"gamergate" + 0.019*"feminism" + 0.019*"men" + 0.015*"like" + 0.007*"equality" + 0.006*"dear" + 0.005*"want" + 0.005*"world" + 0.005*"hate"')
(4, '0.010*"men" + 0.008*"feminism" + 0.007*"equality" + 0.007*"sexist" + 0.007*"go" + 0.005*"know" + 0.005*"see" + 0.005*"want" + 0.005*"look" + 0.005*"god"')

In [ ]:
#10 topics
# Print the topics and their associated keywords
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.029*"men" + 0.027*"women" + 0.014*"gamergate" + 0.012*"equality" + 0.012*"like" + 0.010*"get" + 0.009*"feminism" + 0.006*"much" + 0.006*"rt" + 0.006*"someone"')
(1, '0.013*"shit" + 0.008*"time" + 0.008*"rape" + 0.008*"cat" + 0.008*"gamergate" + 0.008*"gender" + 0.008*"true" + 0.008*"women" + 0.005*"life" + 0.005*"money"')
(2, '0.019*"hate" + 0.017*"women" + 0.011*"gamergate" + 0.011*"men" + 0.006*"say" + 0.006*"fact" + 0.006*"twitter" + 0.006*"personal" + 0.006*"dear" + 0.006*"gender"')
(3, '0.023*"feminism" + 0.010*"hate" + 0.010*"men" + 0.010*"sex" + 0.010*"na" + 0.010*"wan" + 0.010*"u" + 0.007*"go" + 0.007*"ever" + 0.007*"women"')
(4, '0.021*"men" + 0.019*"gamergate" + 0.019*"women" + 0.012*"equality" + 0.012*"feminism" + 0.009*"want" + 0.009*"woman" + 0.007*"rt" + 0.007*"rape" + 0.007*"get"')
(5, '0.021*"gamergate" + 0.019*"like" + 0.014*"women" + 0.012*"feminism" + 0.009*"people" + 0.007*"even" + 0.007*"find" + 0.007*"look" + 0.007*"want" + 0.007*"modern"')
(6, '0.017*"men" + 0.015*"women" + 0.011*"gamergate" + 0.011*"sexist" + 0.011*"like" + 0.008*"people" + 0.008*"real" + 0.008*"feminism" + 0.006*"give" + 0.006*"believe"')
(7, '0.013*"feminism" + 0.011*"equal" + 0.011*"man" + 0.011*"gamergate" + 0.009*"make" + 0.009*"know" + 0.007*"ca" + 0.007*"love" + 0.007*"bad" + 0.007*"stop"')
(8, '0.018*"feminism" + 0.015*"one" + 0.012*"like" + 0.012*"dear" + 0.009*"male" + 0.006*"gamergate" + 0.006*"female" + 0.006*"equality" + 0.006*"people" + 0.006*"instead"')
(9, '0.017*"women" + 0.014*"gamergate" + 0.012*"want" + 0.009*"make" + 0.009*"dear" + 0.009*"gender" + 0.009*"men" + 0.009*"feminism" + 0.006*"think" + 0.006*"rape"')

In [ ]:
#15 topics
# Print the topics and their associated keywords
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.031*"women" + 0.023*"men" + 0.011*"equal" + 0.009*"go" + 0.009*"come" + 0.009*"get" + 0.009*"mean" + 0.009*"make" + 0.009*"feel" + 0.009*"spankafeminist"')
(1, '0.034*"gamergate" + 0.010*"rape" + 0.010*"dear" + 0.010*"feminism" + 0.010*"get" + 0.005*"rights" + 0.005*"alone" + 0.005*"suffering" + 0.005*"real" + 0.005*"able"')
(2, '0.018*"people" + 0.014*"women" + 0.014*"men" + 0.014*"gamergate" + 0.011*"make" + 0.011*"feminism" + 0.011*"could" + 0.007*"reasons" + 0.007*"look" + 0.007*"need"')
(3, '0.017*"gamergate" + 0.013*"honest" + 0.013*"rape" + 0.008*"women" + 0.008*"one" + 0.008*"level" + 0.008*"information" + 0.008*"antifeminism" + 0.008*"literally" + 0.008*"modern"')
(4, '0.027*"men" + 0.010*"spankafeminist" + 0.010*"know" + 0.010*"hate" + 0.010*"feminism" + 0.007*"equality" + 0.007*"women" + 0.007*"ok" + 0.007*"clearly" + 0.007*"things"')
(5, '0.015*"women" + 0.011*"say" + 0.011*"equal" + 0.011*"gamergate" + 0.011*"cat" + 0.008*"gap" + 0.008*"wage" + 0.008*"paid" + 0.008*"hey" + 0.008*"get"')
(6, '0.039*"like" + 0.030*"women" + 0.017*"men" + 0.011*"gamergate" + 0.009*"gender" + 0.009*"equality" + 0.009*"people" + 0.009*"sexism" + 0.009*"sexist" + 0.006*"go"')
(7, '0.051*"feminism" + 0.026*"gamergate" + 0.009*"without" + 0.009*"equality" + 0.008*"women" + 0.007*"welcome" + 0.007*"equal" + 0.007*"want" + 0.007*"one" + 0.007*"see"')
(8, '0.019*"gamergate" + 0.011*"shit" + 0.008*"get" + 0.008*"girls" + 0.008*"boobs" + 0.008*"equality" + 0.008*"one" + 0.008*"sexist" + 0.008*"press" + 0.008*"hate"')
(9, '0.028*"men" + 0.017*"women" + 0.011*"right" + 0.011*"hate" + 0.011*"bad" + 0.011*"shit" + 0.007*"gave" + 0.007*"video" + 0.007*"equality" + 0.007*"stupid"')
(10, '0.010*"told" + 0.010*"ha" + 0.010*"form" + 0.010*"sexual" + 0.010*"personal" + 0.010*"never" + 0.010*"quiet" + 0.005*"throw" + 0.005*"sjws" + 0.005*"intelligence"')
(11, '0.016*"u" + 0.016*"men" + 0.012*"want" + 0.012*"gamergate" + 0.008*"honest" + 0.008*"one" + 0.008*"time" + 0.008*"women" + 0.008*"mother" + 0.008*"know"')
(12, '0.019*"women" + 0.010*"find" + 0.010*"attractive" + 0.010*"ass" + 0.010*"pig" + 0.010*"girls" + 0.010*"stop" + 0.010*"fucking" + 0.010*"man" + 0.010*"lmao"')
(13, '0.012*"women" + 0.009*"sex" + 0.009*"sexist" + 0.009*"feminism" + 0.009*"like" + 0.009*"man" + 0.009*"gamergate" + 0.006*"hope" + 0.006*"exclusive" + 0.006*"heart"')
(14, '0.018*"gamergate" + 0.012*"rape" + 0.009*"feminism" + 0.009*"women" + 0.009*"like" + 0.006*"one" + 0.006*"meninist" + 0.006*"culture" + 0.006*"social" + 0.006*"painted"')

##Feminism None Stance

In [ ]:
#5 topics
# Print the topics and their associated keywords
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.009*"us" + 0.009*"take" + 0.006*"facts" + 0.006*"feel" + 0.006*"get" + 0.006*"time" + 0.006*"hold" + 0.006*"years" + 0.006*"ago" + 0.006*"data"')
(1, '0.008*"mother" + 0.008*"bored" + 0.008*"never" + 0.006*"u" + 0.006*"like" + 0.006*"see" + 0.006*"wax" + 0.006*"tl" + 0.006*"school" + 0.006*"voices"')
(2, '0.010*"like" + 0.010*"research" + 0.007*"ca" + 0.007*"na" + 0.007*"get" + 0.007*"love" + 0.007*"gon" + 0.007*"issues" + 0.007*"peggy" + 0.007*"great"')
(3, '0.016*"one" + 0.010*"towie" + 0.007*"life" + 0.007*"ca" + 0.007*"show" + 0.007*"male" + 0.007*"trying" + 0.007*"made" + 0.007*"people" + 0.007*"either"')
(4, '0.013*"people" + 0.010*"blacklivesmatter" + 0.008*"fuck" + 0.008*"baltimoreriots" + 0.008*"instead" + 0.008*"ever" + 0.008*"maybe" + 0.005*"rape" + 0.005*"young" + 0.005*"gamergate"')

In [ ]:
#10 topics
# print the topics and their associated keywords
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.014*"fuck" + 0.014*"made" + 0.014*"ever" + 0.014*"got" + 0.014*"never" + 0.014*"ta" + 0.014*"data" + 0.014*"true" + 0.007*"feel" + 0.007*"like"')
(1, '0.017*"rape" + 0.017*"male" + 0.012*"ca" + 0.012*"saying" + 0.012*"take" + 0.012*"gamergate" + 0.012*"victims" + 0.012*"instead" + 0.006*"twitter" + 0.006*"things"')
(2, '0.013*"issues" + 0.013*"super" + 0.013*"feminazi" + 0.013*"feminist" + 0.007*"ca" + 0.007*"support" + 0.007*"like" + 0.007*"fat" + 0.007*"see" + 0.007*"rt"')
(3, '0.011*"blacklivesmatter" + 0.011*"gay" + 0.011*"trying" + 0.011*"us" + 0.011*"marriage" + 0.011*"fix" + 0.011*"problems" + 0.011*"baltimoreriots" + 0.006*"job" + 0.006*"ca"')
(4, '0.017*"young" + 0.012*"woman" + 0.012*"god" + 0.012*"con" + 0.012*"colors" + 0.012*"man" + 0.012*"voices" + 0.006*"love" + 0.006*"joke" + 0.006*"politics"')
(5, '0.012*"towie" + 0.012*"school" + 0.012*"years" + 0.012*"ago" + 0.012*"used" + 0.012*"agree" + 0.012*"facts" + 0.012*"die" + 0.006*"even" + 0.006*"nice"')
(6, '0.018*"get" + 0.014*"research" + 0.009*"people" + 0.009*"na" + 0.009*"bored" + 0.009*"gon" + 0.009*"reason" + 0.009*"u" + 0.009*"guy" + 0.009*"give"')
(7, '0.015*"life" + 0.008*"like" + 0.008*"time" + 0.008*"child" + 0.008*"equality" + 0.008*"could" + 0.008*"going" + 0.008*"myth" + 0.008*"dad" + 0.008*"family"')
(8, '0.025*"one" + 0.015*"well" + 0.010*"people" + 0.010*"baltimoreriots" + 0.010*"great" + 0.010*"peggy" + 0.010*"crap" + 0.010*"right" + 0.005*"way" + 0.005*"love"')
(9, '0.013*"need" + 0.013*"show" + 0.013*"mother" + 0.013*"wax" + 0.007*"actually" + 0.007*"love" + 0.007*"sex" + 0.007*"lol" + 0.007*"pls" + 0.007*"people"')

#Women Empwerment

Topic modelling for Women emperment dataset.. we extracted the topics for each stance' tweets separately

In [15]:
df = pd.read_csv('Real_train_women_1190.csv')
df.head()

,ID,target,text,stance
0,1,Women empowerment,عشان يلمع صورته ويعنني تمكين المرأة ويصير ترن...,Against
1,4,Women empowerment,هذا ما يُعرّف بـ'فوبيا المرأة المُتمكنة' آفة ف...,Favor
2,8,Women empowerment,فخورين بنساء الوطن 🇸🇦 وكلنا فخر بتقدم تمكين ا...,Favor
3,9,Women empowerment,ههههههههههههههه ماعليك زمن تمكين المرأة ماراح...,None
4,22,Women empowerment,وين تمكين المرأة؟,None

In [16]:
Tweet=df[df['stance']== 'None']['text'] #choose the stance' tweets for topic modelling
Tweet.head()

3      ههههههههههههههه ماعليك زمن تمكين المرأة ماراح...
4                                     وين تمكين المرأة؟
5     هناك من عاصر زمن تحرير السود من العبودية  وهنا...
23          #تمكين_المرأة من وجهة نظر الديناصورات 🦖 URL
40    واللي عاشو في الفجوه الكونيه اش يسوون 🚶🏻‍♂️  #...
Name: text, dtype: object

In [22]:
#pre-process the tweets before use the LDA model

# Download the necessary resources
nltk.download('punkt')
nltk.download('stopwords')

stop_words = set(stopwords.words("arabic"))
additional_stopwords = ["التمكين", "تمكين_المرأة", "يوم_المراه_العالمي","يوم_المرأة_العالمي","للمرأة","","قائدات_التقنية","المرأه","المرأة","MENTION", "تمكين", "ان","الى","اي","URL","الرجل","الله"]
stop_words.update(additional_stopwords)

def preprocess_arabic(tweet):

    tweet = re.sub(r"http\S+|www\S+|https\S+", "", tweet) # emove URLs
    tweet = re.sub(r"@\w+", "", tweet) # remove usernames and mentions
    tweet = re.sub(r"[^\w\s]", "", tweet)  # remove special characters and numbers
    tweet = re.sub(r"\d+", "", tweet)
    tokens = word_tokenize(tweet) # tokenize the tweet
    filtered_tokens = [token for token in tokens if token.lower() not in stop_words] # remove stopwords

    preprocessed_tweet = " ".join(filtered_tokens)

    return preprocessed_tweet

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [23]:
# apply preprocessing
Tweet= Tweet.apply(preprocess_arabic)
Tweet.head()

3             ههههههههههههههه ماعليك زمن ماراح يسوون شي
4                                                   وين
5     عاصر زمن تحرير السود العبودية وهناك عاصر زمن و...
23                             وجهة نظر الديناصورات URL
40    واللي عاشو الفجوه الكونيه اش يسوون موتمر_تمكين...
Name: text, dtype: object

In [19]:
# create a dictionary
dictionary_Tweets = corpora.Dictionary([tweet.split() for tweet in Tweet])
# convert the tweets into a bag-of-words corpus (counts the frequency of each word)
corpus_Tweets=[]
for tweet in Tweet:
  tweet=tweet.split()
  text= dictionary_Tweets.doc2bow(tweet)
  corpus_Tweets.append(text)
print(corpus_Tweets[:1]) #viewing

[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1)]

In [20]:
num_topics = 5
# perform LDA topic modeling
lda_model = gensim.models.LdaModel(corpus_Tweets, num_topics=num_topics, id2word=dictionary_Tweets, passes=10)

**In the following Stances headings, we printed the topics as 5,10, or 15 number of topics**

##Wonen Against Stance

In [ ]:
#5 topics
# print the topics
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.008*"الرجل" + 0.005*"النساء" + 0.004*"MENTION" + 0.003*"بسبب" + 0.003*"اذا" + 0.002*"الأسرة" + 0.002*"السبب" + 0.002*"المجتمع" + 0.002*"الرجال" + 0.002*"الله"')
(1, '0.004*"MENTION" + 0.004*"النساء" + 0.004*"الرجل" + 0.003*"الرجال" + 0.003*"الدين" + 0.003*"المراه" + 0.003*"او" + 0.003*"العمل" + 0.003*"المجتمع" + 0.003*"URL"')
(2, '0.005*"الرجال" + 0.004*"الشباب" + 0.004*"الرجل" + 0.003*"البلد" + 0.003*"URL" + 0.003*"المراة" + 0.003*"الله" + 0.003*"الي" + 0.003*"MENTION" + 0.003*"زمن"')
(3, '0.006*"الله" + 0.005*"اللي" + 0.005*"الرجل" + 0.004*"المراة" + 0.003*"URL" + 0.003*"والله" + 0.003*"MENTION" + 0.003*"المجتمع" + 0.003*"الا" + 0.003*"حقوق"')
(4, '0.009*"الله" + 0.005*"عصر" + 0.004*"الا" + 0.003*"اللي" + 0.003*"الرجال" + 0.003*"المراة" + 0.003*"والله" + 0.003*"قال" + 0.003*"ضد" + 0.002*"النساء"')

In [ ]:
#10 topics
# Print the topics
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.006*"MENTION" + 0.004*"الرجال" + 0.004*"قال" + 0.003*"النساء" + 0.003*"الرجل" + 0.003*"الطلاق" + 0.003*"حقوق" + 0.003*"وين" + 0.003*"كانت" + 0.003*"حالات"')
(1, '0.009*"الله" + 0.009*"MENTION" + 0.004*"المجتمع" + 0.004*"المراه" + 0.003*"الشباب" + 0.003*"الوصول" + 0.003*"العامة" + 0.003*"الرجال" + 0.003*"أسباب" + 0.003*"الأفكار"')
(2, '0.010*"الرجل" + 0.009*"الله" + 0.007*"اللي" + 0.005*"العمل" + 0.005*"يكون" + 0.004*"الزواج" + 0.003*"للأسف" + 0.003*"URL" + 0.003*"عليها" + 0.003*"الا"')
(3, '0.011*"الله" + 0.007*"URL" + 0.007*"المراة" + 0.005*"عصر" + 0.004*"الشباب" + 0.003*"بدون" + 0.003*"بسبب" + 0.003*"الرجال" + 0.003*"العمل" + 0.003*"الا"')
(4, '0.006*"الرجل" + 0.004*"اذا" + 0.004*"MENTION" + 0.004*"الرجال" + 0.003*"توظيف" + 0.003*"كلها" + 0.003*"الشباب" + 0.003*"طيب" + 0.003*"دول" + 0.003*"النساء"')
(5, '0.012*"MENTION" + 0.011*"الرجل" + 0.005*"والله" + 0.004*"الله" + 0.004*"الا" + 0.004*"النساء" + 0.004*"العالم" + 0.004*"فشل" + 0.003*"بعدين" + 0.003*"نرفض"')
(6, '0.005*"اللي" + 0.005*"المجتمع" + 0.004*"الله" + 0.004*"يتكلمون" + 0.004*"يعني" + 0.004*"الشباب" + 0.003*"الي" + 0.003*"URL" + 0.003*"يؤدي" + 0.003*"عاطل"')
(7, '0.007*"المراة" + 0.006*"شي" + 0.004*"الرجل" + 0.004*"المجتمع" + 0.004*"والله" + 0.004*"اللى" + 0.003*"مو" + 0.003*"العمل" + 0.003*"الغرب" + 0.003*"البلد"')
(8, '0.008*"الرجل" + 0.006*"المراة" + 0.005*"الرجال" + 0.004*"الدول" + 0.004*"URL" + 0.003*"حساب" + 0.003*"خدمة" + 0.003*"زوجها" + 0.003*"كثير" + 0.003*"الأسرة"')
(9, '0.007*"الرجال" + 0.005*"مليون" + 0.004*"الاسره" + 0.004*"الرجل" + 0.004*"عندنا" + 0.004*"السبب" + 0.004*"الدين" + 0.003*"الأسرة" + 0.003*"او" + 0.003*"وهي"')

In [ ]:
#15 topics
# Print the topics
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.018*"الله" + 0.007*"اللي" + 0.005*"الغرب" + 0.005*"يلعن" + 0.004*"الا" + 0.004*"القوانين" + 0.004*"كلها" + 0.004*"مشروع" + 0.004*"عليها" + 0.003*"بسبب"')
(1, '0.004*"قال" + 0.004*"تمكينا" + 0.004*"انت" + 0.004*"مستوى" + 0.004*"العمل" + 0.004*"بالنهاية" + 0.004*"بنات" + 0.004*"يملأ" + 0.002*"اذا" + 0.002*"سبب"')
(2, '0.007*"الرجل" + 0.005*"MENTION" + 0.005*"الشباب" + 0.005*"المراه" + 0.004*"السيارات" + 0.004*"URL" + 0.004*"يتم" + 0.004*"النظام" + 0.004*"الزواج" + 0.004*"عليا"')
(3, '0.010*"الله" + 0.005*"اللي" + 0.005*"حقوق" + 0.004*"وظائف" + 0.004*"السفر" + 0.004*"الا" + 0.004*"عصر" + 0.004*"أسباب" + 0.004*"المراة" + 0.004*"شي"')
(4, '0.005*"الرجال" + 0.005*"URL" + 0.005*"قال" + 0.005*"المراة" + 0.005*"MENTION" + 0.005*"او" + 0.004*"اذا" + 0.004*"الرجل" + 0.004*"عصر" + 0.004*"كبيرة"')
(5, '0.009*"الرجال" + 0.007*"العمل" + 0.006*"اللي" + 0.006*"الرجل" + 0.005*"النساء" + 0.005*"الشباب" + 0.005*"السعودية" + 0.003*"الله" + 0.003*"عشان" + 0.003*"البنات"')
(6, '0.011*"الرجل" + 0.008*"النساء" + 0.006*"URL" + 0.005*"وفي" + 0.005*"يؤدي" + 0.004*"المجتمع" + 0.004*"العمل" + 0.004*"مكان" + 0.004*"وهذا" + 0.004*"الرجال"')
(7, '0.007*"فشل" + 0.005*"عصر" + 0.005*"اللى" + 0.004*"الا" + 0.004*"الرجل" + 0.004*"الهدف" + 0.004*"تمكنت" + 0.004*"دول" + 0.003*"بسبب" + 0.003*"الله"')
(8, '0.006*"الدول" + 0.006*"الله" + 0.006*"اللي" + 0.004*"كانت" + 0.004*"امرأة" + 0.004*"عشان" + 0.004*"قدام" + 0.004*"URL" + 0.004*"الغرب" + 0.004*"المجتمع"')
(9, '0.007*"المراة" + 0.006*"الرجل" + 0.005*"الغرب" + 0.005*"URL" + 0.005*"الدين" + 0.004*"خدمة" + 0.004*"صور" + 0.004*"خير" + 0.004*"زمن" + 0.004*"الا"')
(10, '0.007*"MENTION" + 0.006*"المراه" + 0.004*"كثير" + 0.004*"الدول" + 0.004*"دول" + 0.004*"المنزل" + 0.003*"الله" + 0.003*"الرجال" + 0.003*"حول" + 0.003*"انا"')
(11, '0.008*"المراة" + 0.008*"الله" + 0.008*"والله" + 0.005*"مليون" + 0.005*"الرجال" + 0.004*"حرية" + 0.004*"معين" + 0.004*"الاسره" + 0.004*"ام" + 0.004*"المجتمع"')
(12, '0.014*"MENTION" + 0.005*"المجتمع" + 0.005*"الرجال" + 0.005*"اذا" + 0.005*"الي" + 0.004*"يتكلمون" + 0.004*"الرجل" + 0.004*"المراة" + 0.003*"الطلاق" + 0.003*"عنه"')
(13, '0.005*"المراة" + 0.005*"والله" + 0.005*"الرجل" + 0.003*"يصير" + 0.003*"بالله" + 0.003*"الله" + 0.003*"اليوم" + 0.003*"او" + 0.003*"بيتها" + 0.003*"العيال"')
(14, '0.011*"الرجل" + 0.008*"حساب" + 0.006*"MENTION" + 0.006*"يكون" + 0.006*"يجب" + 0.005*"دور" + 0.004*"العمل" + 0.004*"المبالغة" + 0.004*"الشباب" + 0.003*"زواج"')

##Wonen Favor Stance

In [ ]:
#5 topics
# print the topics
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.009*"السعودية" + 0.008*"الله" + 0.005*"النساء" + 0.004*"العمل" + 0.004*"المجتمع" + 0.004*"URL" + 0.003*"المجالات" + 0.003*"نصف" + 0.003*"خلال" + 0.003*"العالم"')
(1, '0.006*"المجتمع" + 0.005*"الله" + 0.003*"للمرأة" + 0.003*"بن" + 0.003*"السعودية" + 0.003*"محمد" + 0.003*"URL" + 0.003*"سلمان" + 0.003*"اليوم" + 0.003*"الرجل"')
(2, '0.007*"السعودية" + 0.004*"اللي" + 0.003*"بشكل" + 0.003*"الرجل" + 0.002*"يوم" + 0.002*"يوم_المراه_العالمي" + 0.002*"المراة" + 0.002*"المجتمع" + 0.002*"دور" + 0.002*"للمرأة"')
(3, '0.006*"URL" + 0.003*"اليوم" + 0.003*"المجتمع" + 0.003*"رؤية" + 0.003*"دور" + 0.003*"او" + 0.002*"حقوقها" + 0.002*"السعودية" + 0.002*"قائد" + 0.002*"عصر"')
(4, '0.010*"السعودية" + 0.006*"الله" + 0.005*"العمل" + 0.004*"المجالات" + 0.003*"URL" + 0.003*"للمرأة" + 0.003*"الوطن" + 0.003*"المملكة" + 0.002*"يوم" + 0.002*"اليوم"')

In [ ]:
#10 topics
# print the topics
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.005*"عصر" + 0.004*"اللي" + 0.003*"URL" + 0.003*"المراة" + 0.003*"العمل" + 0.003*"عمل" + 0.003*"الله" + 0.003*"اليوم_العالمي_للمرأة" + 0.003*"اذا" + 0.003*"الا"')
(1, '0.006*"للمرأة" + 0.006*"السعودية" + 0.006*"اليوم" + 0.006*"الله" + 0.005*"المجتمع" + 0.005*"URL" + 0.005*"او" + 0.004*"العالم" + 0.004*"تكون" + 0.004*"الرجل"')
(2, '0.010*"المجتمع" + 0.005*"نصف" + 0.005*"العمل" + 0.004*"المساواة" + 0.004*"السعودية" + 0.004*"قائد" + 0.004*"دور" + 0.003*"الجنسين" + 0.003*"اللي" + 0.003*"او"')
(3, '0.013*"السعودية" + 0.005*"URL" + 0.004*"يوم_المرأة_العالمي" + 0.004*"عام" + 0.004*"قطاع" + 0.004*"يوم" + 0.004*"اللي" + 0.004*"قائدات_التقنية" + 0.004*"الاتصالات" + 0.003*"المعلومات"')
(4, '0.006*"السعودية" + 0.005*"الله" + 0.005*"تحقيق" + 0.004*"URL" + 0.004*"الدولة" + 0.004*"حول" + 0.003*"وفي" + 0.003*"رؤية" + 0.003*"للمرأة" + 0.003*"المجالات"')
(5, '0.006*"السعودية" + 0.005*"الله" + 0.004*"النساء" + 0.004*"URL" + 0.004*"العمل" + 0.003*"المراة" + 0.003*"يوم" + 0.003*"علي" + 0.003*"للمرأة" + 0.003*"المملكة"')
(6, '0.008*"الله" + 0.007*"السعودية" + 0.006*"URL" + 0.005*"سلمان" + 0.004*"النساء" + 0.004*"بن" + 0.003*"رؤية" + 0.003*"محمد" + 0.003*"الشباب" + 0.003*"الرجل"')
(7, '0.007*"العمل" + 0.006*"السعودية" + 0.004*"MENTION" + 0.004*"المجالات" + 0.003*"الوطن" + 0.003*"فى" + 0.003*"جدا" + 0.003*"حقوق" + 0.002*"المملكة" + 0.002*"الرجل"')
(8, '0.008*"السعودية" + 0.004*"الله" + 0.004*"للمرأة" + 0.004*"المجتمع" + 0.004*"المراة" + 0.004*"أهمية" + 0.003*"المجالات" + 0.003*"دعم" + 0.003*"URL" + 0.003*"كانت"')
(9, '0.006*"الله" + 0.005*"المجتمع" + 0.004*"السعودية" + 0.004*"المراه" + 0.004*"ولي" + 0.004*"سلمان" + 0.004*"محمد" + 0.004*"العهد" + 0.003*"نساء" + 0.003*"بن"')

In [ ]:
#15 topics
# print the topics
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.006*"قطاع" + 0.005*"الاتصالات" + 0.005*"المعلومات" + 0.005*"وتقنية" + 0.004*"المملكة" + 0.004*"العمل" + 0.003*"كانت" + 0.003*"ملتقى" + 0.003*"دور" + 0.003*"فاطمة"')
(1, '0.007*"المجتمع" + 0.007*"السعودية" + 0.005*"URL" + 0.003*"النساء" + 0.003*"رؤية" + 0.003*"بفضل" + 0.003*"حقوقها" + 0.003*"سلمان" + 0.003*"المراة" + 0.003*"دور"')
(2, '0.011*"السعودية" + 0.008*"رؤية" + 0.005*"المملكة" + 0.004*"دعم" + 0.003*"URL" + 0.003*"أهمية" + 0.003*"تحقيق" + 0.003*"النساء" + 0.003*"التنمية" + 0.003*"أهداف"')
(3, '0.006*"السعودية" + 0.005*"العالم" + 0.004*"رؤية" + 0.003*"URL" + 0.003*"خلال" + 0.003*"اليوم" + 0.003*"والله" + 0.003*"عنها" + 0.003*"MENTION" + 0.003*"ضد"')
(4, '0.007*"عصر" + 0.007*"السعودية" + 0.007*"المراة" + 0.006*"النساء" + 0.005*"المجتمع" + 0.005*"كانت" + 0.003*"الدول" + 0.003*"بأن" + 0.003*"خلال" + 0.003*"يعني"')
(5, '0.007*"URL" + 0.006*"السعودية" + 0.004*"اليوم" + 0.003*"المجالات" + 0.003*"المحاسبة" + 0.003*"اللي" + 0.002*"الرجال" + 0.002*"بدون" + 0.002*"العمل" + 0.002*"البنات"')
(6, '0.014*"السعودية" + 0.010*"سلمان" + 0.010*"محمد" + 0.009*"المجتمع" + 0.009*"بن" + 0.008*"ولي" + 0.007*"نصف" + 0.006*"العهد" + 0.005*"رؤية" + 0.005*"المجالات"')
(7, '0.007*"السعودية" + 0.006*"المجالات" + 0.004*"توجه" + 0.004*"دور" + 0.003*"حساب" + 0.003*"يعني" + 0.003*"وهذا" + 0.003*"او" + 0.003*"حول" + 0.003*"العالم"')
(8, '0.010*"السعودية" + 0.006*"الوطن" + 0.005*"المجالات" + 0.004*"الرؤية" + 0.004*"URL" + 0.004*"رؤية__واقع_يتحقق" + 0.003*"وهذا" + 0.003*"رؤية" + 0.003*"المجتمع" + 0.003*"الحياة"')
(9, '0.007*"المجتمع" + 0.006*"URL" + 0.005*"كانت" + 0.004*"النساء" + 0.004*"تكون" + 0.003*"الحياة" + 0.003*"المراة" + 0.002*"المراه" + 0.002*"المجالات" + 0.002*"مجالات"')
(10, '0.006*"URL" + 0.005*"المراة" + 0.003*"او" + 0.003*"لان" + 0.003*"وربي" + 0.002*"مجتمع" + 0.002*"مسيرة" + 0.002*"السعودية" + 0.002*"القرار" + 0.002*"بال"')
(11, '0.010*"URL" + 0.004*"عصر" + 0.004*"زمن" + 0.004*"المجتمع" + 0.003*"MENTION" + 0.003*"المملكة" + 0.003*"حقوق" + 0.003*"بشكل" + 0.003*"عام" + 0.003*"السعودية"')
(12, '0.007*"العمل" + 0.005*"قائد" + 0.005*"اليوم" + 0.004*"الدولة" + 0.004*"وفي" + 0.004*"URL" + 0.003*"يوم" + 0.003*"شكرا" + 0.003*"اللي" + 0.003*"المجتمع"')
(13, '0.012*"السعودية" + 0.005*"العمل" + 0.005*"اليوم_العالمي_للمرأة" + 0.004*"URL" + 0.004*"جهود" + 0.003*"يوم" + 0.003*"قيادتنا" + 0.003*"فى" + 0.003*"بكل" + 0.003*"الدولة"')
(14, '0.010*"المراه" + 0.003*"او" + 0.003*"القيادية" + 0.003*"شي" + 0.003*"المجتمع" + 0.003*"العدل" + 0.003*"العربية" + 0.003*"ليش" + 0.003*"الجنسين" + 0.003*"التحديات"')

##Wonen None Stance

In [ ]:
#5 topics
# Print the topics
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.010*"تمكين" + 0.007*"غلط" + 0.007*"الله" + 0.007*"تمكين_المرأة" + 0.007*"فاهم" + 0.007*"الخصوصية" + 0.007*"الجمعية" + 0.007*"المعاقات" + 0.004*"وين" + 0.004*"الاعلام"')
(1, '0.034*"تمكين" + 0.029*"المرأة" + 0.020*"URL" + 0.007*"المرأه" + 0.006*"زمن" + 0.006*"شي" + 0.006*"تمكين_المرأة" + 0.006*"ان" + 0.006*"الي" + 0.004*"الحياة"')
(2, '0.011*"تمكين" + 0.008*"المرأة" + 0.008*"والمنشأ" + 0.008*"الأصل" + 0.008*"الشارع" + 0.008*"تمكين_المرأة" + 0.008*"اللي" + 0.008*"الوحيد" + 0.008*"يقدر" + 0.008*"مدروسة"')
(3, '0.036*"تمكين" + 0.033*"المرأة" + 0.014*"URL" + 0.009*"زمن" + 0.006*"نفسية" + 0.006*"تعي" + 0.006*"السعودية" + 0.006*"الله" + 0.006*"عاصر" + 0.006*"سياسة"')
(4, '0.033*"المرأة" + 0.030*"تمكين" + 0.011*"URL" + 0.006*"بدعوى" + 0.006*"الحريه" + 0.006*"القبض_علي_مدعيه_النبوه" + 0.006*"غلط" + 0.006*"المشاريع" + 0.006*"مهارات" + 0.006*"المصرية"')

#Covid-19 Vaccine

Topic modelling for Covid-19 dataset.. we extracted the topics for each stance' tweets separately

In [24]:
df = pd.read_csv('Real_covid19_train_tweets.csv')
df.head()

                                               tweet  label
0  Yup no thank you!!! How about a vaccine for ca...      0
1  Is it supposed to make us feel better that 3 o...      0
2  Sorry. Don’t care. Take your vaccine and shove...      0
3  @Charbros1 @piersmorgan What makes you think i...      0
4  @RepDanCrenshaw As a 20 plus year paramedic I’...      0

In [25]:
Tweet=df[df['label']== 1]['tweet'] #choose the stance' tweets for topic modelling, 0:against, 1: none, 2:favor
Tweet.head()

535    Allina Health seeks volunteers for COVID-19 va...
536    Pfizer, BioNTech apply for coronavirus vaccine...
537    Coronavirus vaccine just WEEKS away as UK hosp...
538    India Today: Coronavirus vaccine update: Bhara...
539    Well well the truth about why this vaccine has...
Name: tweet, dtype: object

In [26]:
#pre-process the tweets before use the LDA model
nltk.download('punkt')
nltk.download('stopwords')
stops = set(stopwords.words("english"))
additional_stopwords = ["vaccine", "vaccines", "news", "covid-19"]
stops.update(additional_stopwords)

def preprocess(tweet):
  tokenlist=[]
  tweet = re.sub(r"http\S+|www\S+|https\S+", "", tweet)  # remove URLs
  tweet = re.sub(r"@\w+", "", tweet)  # remove usernames
  tokens = nltk.word_tokenize(tweet) #tokenization
  tokenlist= [w.lower() for w in tokens if w.isalpha()] #make each token in owest case and remove numbers and punctuations

  tokenlist= [word for word in tokenlist if not word in stops] #remove stop words
  return ' '.join([w for w in tokenlist])

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [27]:
# apply preprocessing
Tweet= Tweet.apply(preprocess)
Tweet.head()

535             allina health seeks volunteers trial via
536    pfizer biontech apply coronavirus approval europe
537    coronavirus weeks away uk hospitals told prepa...
538    india today coronavirus update bharat biotech ...
539            well well truth pushed vigourous research
Name: tweet, dtype: object

In [28]:
# create a dictionary
dictionary_Tweets = corpora.Dictionary([tweet.split() for tweet in Tweet])
# convert the tweets into a bag-of-words corpus (counts the frequency of each word)
corpus_Tweets=[]
for tweet in Tweet:
  tweet=tweet.split()
  text= dictionary_Tweets.doc2bow(tweet)
  corpus_Tweets.append(text)
print(corpus_Tweets[:1]) #viewing

[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1)]

In [29]:
num_topics = 10
# built LDA model
lda_model = gensim.models.LdaModel(corpus_Tweets, num_topics=num_topics, id2word=dictionary_Tweets, passes=10)

**In the following Stances headings, we printed the topics as 5 or 10 number of topics**

##Covid Favor Stance

In [ ]:
#5 topics
# Print the topics
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.024*"news" + 0.024*"pfizer" + 0.023*"effective" + 0.020*"coronavirus" + 0.011*"great" + 0.011*"good" + 0.009*"people" + 0.009*"take" + 0.007*"biontech" + 0.006*"covid"')
(1, '0.018*"news" + 0.015*"effective" + 0.015*"good" + 0.013*"one" + 0.011*"pfizer" + 0.009*"get" + 0.009*"coronavirus" + 0.008*"people" + 0.007*"data" + 0.007*"trial"')
(2, '0.031*"news" + 0.014*"great" + 0.012*"get" + 0.011*"good" + 0.008*"pfizer" + 0.008*"first" + 0.007*"effective" + 0.006*"us" + 0.006*"candidate" + 0.006*"week"')
(3, '0.023*"news" + 0.022*"pfizer" + 0.021*"good" + 0.011*"effective" + 0.007*"amp" + 0.007*"great" + 0.007*"one" + 0.005*"year" + 0.005*"results" + 0.005*"time"')
(4, '0.019*"coronavirus" + 0.018*"news" + 0.014*"get" + 0.010*"soon" + 0.010*"pfizer" + 0.009*"end" + 0.008*"still" + 0.008*"amp" + 0.007*"good" + 0.007*"take"')

In [ ]:
#10
# Print the topics
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.042*"pfizer" + 0.039*"effective" + 0.032*"good" + 0.019*"great" + 0.018*"coronavirus" + 0.013*"first" + 0.011*"biontech" + 0.008*"results" + 0.008*"science" + 0.008*"early"')
(1, '0.018*"coronavirus" + 0.012*"hope" + 0.011*"take" + 0.010*"pfizer" + 0.010*"effective" + 0.010*"first" + 0.008*"good" + 0.008*"pandemic" + 0.008*"potential" + 0.008*"world"')
(2, '0.021*"get" + 0.014*"good" + 0.010*"like" + 0.007*"still" + 0.007*"vaccinated" + 0.007*"take" + 0.007*"one" + 0.006*"anti" + 0.006*"safety" + 0.006*"going"')
(3, '0.010*"pfizer" + 0.009*"one" + 0.007*"covid" + 0.007*"pandemic" + 0.007*"take" + 0.006*"people" + 0.006*"great" + 0.006*"today" + 0.006*"get" + 0.006*"safe"')
(4, '0.028*"effective" + 0.015*"pfizer" + 0.015*"good" + 0.012*"says" + 0.012*"candidate" + 0.010*"virus" + 0.010*"via" + 0.010*"manufacturer" + 0.008*"biontech" + 0.007*"get"')
(5, '0.019*"good" + 0.012*"get" + 0.009*"people" + 0.009*"one" + 0.008*"better" + 0.008*"time" + 0.008*"getting" + 0.008*"amp" + 0.008*"hopefully" + 0.006*"need"')
(6, '0.017*"get" + 0.017*"coronavirus" + 0.015*"good" + 0.012*"take" + 0.010*"effective" + 0.009*"work" + 0.008*"people" + 0.007*"week" + 0.007*"wo" + 0.007*"end"')
(7, '0.028*"pfizer" + 0.015*"fingers" + 0.015*"crossed" + 0.014*"effective" + 0.013*"end" + 0.009*"light" + 0.009*"tunnel" + 0.008*"trust" + 0.008*"next" + 0.008*"trump"')
(8, '0.022*"pfizer" + 0.018*"effective" + 0.017*"coronavirus" + 0.011*"data" + 0.010*"great" + 0.008*"trial" + 0.007*"would" + 0.006*"immune" + 0.006*"give" + 0.006*"early"')
(9, '0.019*"coronavirus" + 0.014*"get" + 0.012*"us" + 0.011*"amp" + 0.011*"great" + 0.010*"good" + 0.010*"people" + 0.008*"would" + 0.007*"back" + 0.007*"pfizer"')

##Covid Against Stance

In [ ]:
#5 topics
#print the topics
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.013*"take" + 0.011*"fuck" + 0.011*"effective" + 0.010*"people" + 0.009*"coronavirus" + 0.008*"pfizer" + 0.007*"want" + 0.005*"amp" + 0.005*"going" + 0.005*"get"')
(1, '0.011*"people" + 0.010*"immune" + 0.009*"get" + 0.009*"covid" + 0.008*"system" + 0.008*"like" + 0.007*"know" + 0.007*"taking" + 0.007*"flu" + 0.006*"us"')
(2, '0.021*"take" + 0.013*"years" + 0.013*"taking" + 0.012*"coronavirus" + 0.011*"people" + 0.009*"still" + 0.009*"flu" + 0.008*"developed" + 0.008*"months" + 0.007*"rate"')
(3, '0.015*"need" + 0.012*"virus" + 0.012*"coronavirus" + 0.012*"thanks" + 0.007*"dna" + 0.006*"people" + 0.006*"immune" + 0.006*"effective" + 0.005*"know" + 0.005*"rate"')
(4, '0.021*"coronavirus" + 0.020*"take" + 0.010*"dna" + 0.009*"covid" + 0.008*"even" + 0.008*"effective" + 0.008*"virus" + 0.007*"control" + 0.007*"get" + 0.007*"flu"')

In [ ]:
#10 topics
# print the topics
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.013*"dna" + 0.011*"effective" + 0.010*"coronavirus" + 0.010*"amp" + 0.008*"mrna" + 0.007*"know" + 0.006*"people" + 0.006*"pfizer" + 0.005*"taking" + 0.005*"effects"')
(1, '0.013*"coronavirus" + 0.010*"people" + 0.010*"virus" + 0.009*"effective" + 0.009*"like" + 0.009*"still" + 0.008*"need" + 0.008*"years" + 0.008*"much" + 0.007*"flu"')
(2, '0.014*"fuck" + 0.014*"effective" + 0.011*"thanks" + 0.011*"want" + 0.010*"coronavirus" + 0.010*"get" + 0.010*"take" + 0.009*"trust" + 0.007*"much" + 0.007*"rate"')
(3, '0.018*"coronavirus" + 0.012*"flu" + 0.012*"people" + 0.011*"would" + 0.011*"dna" + 0.010*"control" + 0.009*"push" + 0.009*"like" + 0.009*"amp" + 0.008*"altering"')
(4, '0.023*"take" + 0.009*"effective" + 0.009*"covid" + 0.008*"us" + 0.008*"coronavirus" + 0.008*"going" + 0.008*"want" + 0.007*"get" + 0.007*"years" + 0.007*"thanks"')
(5, '0.015*"coronavirus" + 0.011*"take" + 0.009*"people" + 0.008*"pass" + 0.007*"rate" + 0.007*"testing" + 0.007*"pfizer" + 0.007*"ready" + 0.005*"serious" + 0.005*"virus"')
(6, '0.035*"take" + 0.014*"one" + 0.012*"years" + 0.011*"coronavirus" + 0.010*"virus" + 0.010*"still" + 0.009*"developed" + 0.008*"first" + 0.008*"fuck" + 0.008*"want"')
(7, '0.012*"world" + 0.011*"even" + 0.011*"coronavirus" + 0.009*"know" + 0.009*"flu" + 0.009*"virus" + 0.009*"new" + 0.008*"effects" + 0.008*"side" + 0.006*"rushed"')
(8, '0.017*"coronavirus" + 0.014*"take" + 0.013*"effective" + 0.011*"less" + 0.011*"thanks" + 0.010*"need" + 0.010*"immune" + 0.010*"flu" + 0.010*"get" + 0.009*"rate"')
(9, '0.021*"take" + 0.018*"people" + 0.010*"need" + 0.009*"fuck" + 0.008*"health" + 0.008*"rushed" + 0.008*"first" + 0.007*"virus" + 0.007*"taking" + 0.006*"amp"')

##Covid None Stance

In [ ]:
#10 topics
#print the topics
topics = lda_model.print_topics(num_topics=num_topics)
for topic in topics:
    print(topic)

(0, '0.021*"coronavirus" + 0.009*"amp" + 0.009*"biden" + 0.006*"doses" + 0.005*"pfizer" + 0.005*"one" + 0.005*"first" + 0.005*"trump" + 0.005*"already" + 0.005*"oxford"')
(1, '0.020*"coronavirus" + 0.015*"effective" + 0.014*"pfizer" + 0.011*"moderna" + 0.011*"election" + 0.010*"according" + 0.010*"say" + 0.009*"safe" + 0.008*"amp" + 0.008*"know"')
(2, '0.027*"pfizer" + 0.021*"coronavirus" + 0.012*"trials" + 0.011*"trial" + 0.011*"china" + 0.008*"virus" + 0.008*"covid" + 0.007*"biontech" + 0.006*"one" + 0.005*"effective"')
(3, '0.019*"coronavirus" + 0.014*"says" + 0.008*"trials" + 0.008*"good" + 0.007*"new" + 0.007*"could" + 0.007*"trump" + 0.007*"pfizer" + 0.006*"get" + 0.005*"vaccination"')
(4, '0.013*"coronavirus" + 0.012*"would" + 0.012*"get" + 0.009*"people" + 0.008*"via" + 0.008*"first" + 0.007*"expected" + 0.007*"said" + 0.006*"pfizer" + 0.005*"million"')
(5, '0.014*"coronavirus" + 0.009*"pfizer" + 0.009*"uk" + 0.009*"india" + 0.007*"first" + 0.007*"good" + 0.005*"says" + 0.005*"via" + 0.005*"pfe" + 0.005*"christmas"')
(6, '0.020*"coronavirus" + 0.011*"health" + 0.010*"available" + 0.007*"mrna" + 0.007*"pfizer" + 0.006*"get" + 0.006*"early" + 0.006*"says" + 0.006*"doses" + 0.006*"first"')
(7, '0.018*"coronavirus" + 0.016*"pfizer" + 0.016*"first" + 0.015*"uk" + 0.013*"get" + 0.010*"effective" + 0.009*"week" + 0.009*"could" + 0.007*"early" + 0.007*"trial"')
(8, '0.008*"virus" + 0.007*"pfizer" + 0.007*"covid" + 0.007*"people" + 0.006*"hcq" + 0.006*"india" + 0.006*"found" + 0.006*"children" + 0.005*"biontech" + 0.005*"use"')
(9, '0.038*"coronavirus" + 0.033*"pfizer" + 0.031*"says" + 0.030*"effective" + 0.014*"analysis" + 0.014*"shows" + 0.010*"early" + 0.009*"data" + 0.008*"first" + 0.007*"candidate"')